### PR TITLE
Updated builders to use GitHub Actions

### LINKED ISSUE #97: Attempt to move building to GitHub Actions
Inspired by [other projects](https://github.com/Diapolo10/Tsukasa-credit-card-gag-scam/blob/main/.github/workflows/github_release.yml#L43-L94) it _seems_ that we can downsize our build procedures immensely by moving to GitHub Actions, powered by `nuitka` (since we have a `setup.py`, using [this](https://github.com/Nuitka/Nuitka/blob/develop/README.rst#use-case-5--setuptools-wheels)).

IF this works as advertised, we can easily create builds on GitHub Actions. However, we would still need all of the fluff like NSIS and Debian metadata to make installers and properly register the executable in the OS.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #97

This PR:

 - Updates the build process to run on GitHub Actions.

### CODE REVIEW

**Comment by qstokkink** [comment]
@egbertbouman I'm getting the following message when running the completed build on my machine:

```bash
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pystray/_appindicator.py", line 24, in <module>
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/gi/__init__.py", line 122, in require_version
ValueError: Namespace AppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 141, in run
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/cx_Freeze/initscripts/console.py", line 25, in run
  File "src/tribler/run.py", line 14, in <module>
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pystray/__init__.py", line 64, in <module>
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pystray/__init__.py", line 56, in backend
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pystray/__init__.py", line 28, in appindicator
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pystray/_appindicator.py", line 27, in <module>
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/gi/__init__.py", line 122, in require_version
ValueError: Namespace AyatanaAppIndicator3 not available
```

Using these apt packages on the builder:

```bash
sudo apt-get install -y --allow-downgrades alien cpio=2.13+dfsg-7 devscripts fakeroot libgirepository1.0-dev rpm libayatana-appindicator3-dev gir1.2-ayatanaappindicator3-0.1
```

Have you seen this before (/do you happen to know if I'm missing some package)?

**Comment by egbertbouman** [comment]
If I remember correctly, `pystray` will first attempt to use `AppIndicator3` and if that fails it will try `AyatanaAppIndicator3`.
You could try installing `gir1.2-appindicator3-0.1` as well.

**Comment by qstokkink** [comment]
@egbertbouman thanks, I just added that. I'm still getting the same error though. 🤔 I'll keep digging.

**Comment by qstokkink** [comment]
😮 [it](https://github.com/qstokkink/TriblerExperimental/actions/runs/10262358268?pr=107) works on Ubuntu! Now I need to figure out which of the 100 magical fixes actually fixed it.

**Comment by qstokkink** [comment]
Alright, to give this some closure: the only package I ended up needing is `gir1.2-gtk-4.0`.

**Comment by egbertbouman** [comment]
I guess this means you're now using the GTK backend.
Just a heads up that according to the [docs](https://pystray.readthedocs.io/en/latest/usage.html#selecting-a-backend) an additional third party plugin may be needed to produce a visible icon.

**Comment by qstokkink** [comment]
🤔 I guess that's not ideal.. but this is the only backend works on my Ubuntu machine out-of-the-box.

**Comment by qstokkink** [comment]
<details> <summary>Nevermind this message, my antivirus removed the libtorrent library 🥲 </summary>
We might have some version inconsistency/incompatibility:

error on run

Pip tells me that it installed `libtorrent-1.2.19`.
</details>

**Comment by qstokkink** [comment]
Alright, Windows also seems to work🎉 Sort of: double clicking a torrent file does not download it. I think that's a separate issue though.

**Comment by qstokkink** [comment]
I'm not seeing any errors on Mac. I'll have to check on a VM or something whether everything is O.K. there.

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
@egbertbouman I still want to switch `pull_request` to `workflow_dispatch` but other than that, I'm done. Could you give this a review?

**Comment by egbertbouman** [comment]
Looks good to me.

Do you still want Jenkins as a fallback? It's still needed for signing the Mac build, so we can't get rid of it entirely.

**Comment by qstokkink** [comment]
Thanks, I'll turn this into `workflow_dispatch` and get this merged.

Long term, I'd like* everything to be on GitHub Actions, including signing:

- Windows signing should be reasonably easy with our setup by just using GitHub secrets.
- Mac _could_ be a two-step process. First we could hook our machine in as a "self-hosted runner" into GitHub before using a GitHub-secrets approach. I'm not sure if it is smarter to just do a one-shot port though.

I don't think you can transfer secrets between repos, so I think it would be better to wait until `highlander` makes its way into `Tribler/Tribler`.

*_I believe GitHub Actions and Jenkins do mostly the same thing so I'd like to keep only one to lessen our maintenance load._

**Comment by qstokkink** [comment]
validate

**Review by egbertbouman — APPROVED** [review]

**Pull request merged**
