### PR TITLE
Add integration tests to validate action

### LINKED ISSUE #63: Run integration test on validate
The tests in `src/tribler/test_integration/` were meant to run when validating a PR. However, they have never been hooked in. This should happen.

This works locally:
```cmd
cd src
set PYTHONPATH=../pyipv8
python.exe -m unittest -k tribler.test_integration
```

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #63

This PR:

 - Adds a integration test step to the validation action.

### CODE REVIEW

**Comment by qstokkink** [comment]
validate

**Review by egbertbouman — COMMENTED** [review]
Could you please explain why we need PowerShell here?

**Comment by qstokkink** [comment]
Yes.

**Review by egbertbouman — APPROVED** [review]
OK, it's clear now.

**Pull request merged**
